#!/bin/sh

# syntatic sugar to kill a program (if needed)
# and start it
function run {
	if pgrep $1 ;
	then
		pkill $1
	fi
	$@ &
}

##### AUTOSTART ######
run sxhkd -c ~/.config/bspwm/sxhkdrc -r ~/.sxhkd-out.log
picom --config ~/config/picom.conf &
run nm-applet
run numlockx on
run blueman-tray
run blueberry-tray
run volumeicon
#run redshift-gtk
run nitrogen --restore
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
~/config/polybar/launch.sh

##### MONITORS ######
# TODO handle dual screen
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

##### BSPWM CFG #####
bspc config border_width		2
bspc config window_gap			10
bspc config top_padding			20
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_padding		0
bspc config single_monocle		false
bspc config click_to_focus		true
bspc config split_ratio			0.50
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner

##### BSPWM windows colors #####
# using nord dark colorscheme
bspc config normal_border_color		"#2E3440"
bspc config active_border_color		"#88C0D0"
bspc config focused_border_color	"#88C0D0"
bspc config presel_feedback_color	"#4C566A"
bspc config urgent_border_color		"#BF616A"

##### BSPWM floating rules #####
bspc rule -a Gimp state=floating follow=on
bspc rule -a dialog state=floating follow=on focus=on
bspc rule -a error state=floating follow=on
bspc rule -a download state=floating follow=on
bspc rule -a Arandr state=floating follow=on
bspc rule -a Steam state=floating follow=on focus=on
bspc rule -a branchdialog state=floating follow=on
bspc rule -a confirm state=floating follow=on
bspc rule -a notification state=floating
bspc rule -a file_progress state=floating
bspc rule -a arcolinux-logout state=floating
bspc rule -a toolbar state=floating
bspc rule -a makebranch state=floating
bspc rule -a splash state=floating
bspc rule -a 'Open File' state=floating
bspc rule -a Galculator state=floating

##### Scratchpads #####
bspc rule -a mathspad sticky=on state=floating hidden=on
# singleton
if [ -z $(xdotool search --class mathspad) ]; then
	run termite --class mathspad -e python3
fi
