#!/bin/sh

declare options=("alacritty
bash
bspwm
nvim
zsh
vim
sway
quit")

cmd="dmenu -c -l 20 -i -p Dotfiles:"

if [ $XDG_SESSION_TYPE == "wayland" ]
then
	cmd="wofi -d -p Edit configuration:"
fi

choice=$(echo -e "${options[@]}" | $cmd)

case "$choice" in
	alacritty) choice="$HOME/.config/alacritty/alacritty.yml";;
	bspwm) choice="$HOME/.config/bspwm/bspwmrc";;
	bash) choice="$HOME/.bashrc";;
	nvim) choice="$HOME/.config/nvim/init.vim";;
	sway) choice="$HOME/.config/sway/config";;
	quit) exit 1;;
	vim) choice="$HOME/.vimrc";;
	zsh)
		if [ -f "$HOME/.zshrc-personal" ]; then
			choice="$HOME/.zshrc-personal"
		else
			choice="$HOME/.zshrc"
		fi
	;;
	*) exit 0;;
esac

alacritty -e $EDITOR $choice
